POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QyIiwiaWQiOiI2NmNmNTgyZWVhNzkyMzhlOTk5NTM4MmUiLCJpYXQiOjE3MjQ4NjQ1NjZ9.ZRIHRmpuHrXPnAbjE0lrHAg_HrexN1dA8CAJwfCkv7M

{
  "title": "Other users blog",
  "author": "John Doe",
  "url": "http://johnsblog.com",
  "likes": 5
}